name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: ðŸ› ï¸ Build and Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    
    steps:
    - name: ðŸ‘¨â€ðŸ’» Checkout code
      uses: actions/checkout@v4
      
    - name: ðŸ‘¨â€ðŸ”§ Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: ðŸŽ’ Restore dependencies
      run: dotnet restore
      
    - name: ðŸ› ï¸ Build solution
      run: dotnet build --no-restore --configuration Release
    
    - name: ðŸ§ª Run TUnit tests
      if: always()
      run: dotnet run --project ./tests/Recipers.Api.TUnitTests/Recipers.Api.TUnitTests.csproj --configuration Release --no-build --report-trx --coverage --coverage-output-format cobertura 
      
    - name: ðŸ“ Generate coverage report
      if: always()
      env:
        REPORTGENERATOR_LICENSE: ${{ secrets.REPORTGENERATOR_LICENSE }}
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:./tests/**/*.cobertura.xml -targetdir:./coverage/report -reporttypes:"MarkdownSummaryGithub;Html;Cobertura" "-classfilters:-Recipers.Api.Tests.*;-Recipers.Api.TUnitTests.*"
        if [ -f ./coverage/report/SummaryGithub.md ]; then
          cat ./coverage/report/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: ðŸ“¦ Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: ./coverage/report
    
    - name: ðŸ§ª Run xunit tests
      if: always()
      run: dotnet run --project ./tests/Recipers.Api.Tests/Recipers.Api.Tests.csproj --configuration Release --no-build

    - name: ðŸ›« Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          ./tests/**/*.trx
        check_name: Test Results
        comment_mode: off
        
    - name: ðŸ“¦ Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: './tests/**/*.trx'
